# Site Settings
title: HCI2
description: ""
baseurl: ""
url: ""
author: "Angus P, Chris C, Ben S, Kerel K"
author_avatar: ""

theme_light_blue: "#0093bd"
theme_dark_blue: "#002e5f"
theme_red: "#d50032"
theme_dark_gray: "#252525"

# Main Navigation (Manual)
navigation:
 - text: Home
   url: /

# Build Settings
paginate: 3
paginate_path: "posts/page:num"
markdown: kramdown
permalink: pretty
highlighter: rouge
gems: [jekyll-paginate]
sass:
  style: compressed


# Addition content types
# collections:
#   projects:
#     output: false
#   unlisted:
#     output: true
#     layout: clear
#     permalink: /unlisted/:path/

